services:
  - type: web
    name: emotitune-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn -b 0.0.0.0:10000 app.main:app
    plan: free
    region: oregon
    branch: main
    runtime: python
    repo: https://github.com/shashwat-verma-01/EmotiTuneApp
    rootDir: backend
